name: Publish
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        run: nuget restore HabboLauncher.sln
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Build Desktop App
        run: msbuild HabboLauncher.sln /p:Configuration=Release
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin\Release\HabboLauncher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
